In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

The purpose of this notebook is to develop a supervised machine learning to predict the type of flowers by 4 figures ( parameters) of a flower

In this part we define a dataset with the name of IRIS, so it is not DataFrame from Pandas , however, if we want to see data we have to use the following comand

iris.data\

In [ ]:
iris=datasets.load_iris()# to access the data iris

In [ ]:
iris.data.shape# to know the rows and columns

(150, 4)

In [ ]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In this dtaset we have 2 arrays which we have
1. iris.data which includes 4 features of flowers
2. iris.target which includes the type of iris flowers

In [ ]:
iris.feature_names  # calling the columns

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris_df=pd.DataFrame(iris.data,columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
iris_df['target']=iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

KNN mathod

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski',p=2) # 3 here is we tell it to check the nearest 3\\\mi=nkowski is the formula\\\\p is the euqidian(1) or manhatten or minkowski(2)
x = iris.data
y = iris.target
knn.fit(x, y) # make connection

KNeighborsClassifier()

**In the prediction, we give the fitures of the new object to the fitted KNN and then the KNN model idetifies the class of this object**.

knn.predict gives us the class of each new object based on the fitted data

In [ ]:
x_new=np.array([1,1,2,2])
knn.predict([x_new])    # see the number in the array nd match it with the next code(iris.target_names)  , so the array([0]) is setosa

array([0])

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
x_new=np.array([1,5,21,2])
knn.predict([x_new])

array([2])

code to split data into traning and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3,stratify=iris.target)

In [ ]:
x_train.shape

(105, 4)

In [ ]:
x_test.shape

(45, 4)

In [ ]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
y_predict=knn.predict(x_test)
y_predict

array([0, 1, 2, 1, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1,
       0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 2, 1, 1, 1, 0, 0,
       0])

In [ ]:
knn.score(x_test,y_test)

0.9777777777777777